version: '3.3'

services:

  # First application
  app-1:
    depends_on:
      - mariadb-1
    build:
      context: ./app-1
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8001:8083
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://mariadb-1:3306/app?useSSL=false",
        "spring.datasource.username" : "user",
        "spring.datasource.password" : "mjuyhnbgtrfvcde",
        "spring.datasource.driver-class-name" : "org.mariadb.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "endpoint.ms2-url" : "http://app-2"
        }'
    stdin_open: true
    tty: true

  # Second application
  app-2:
    depends_on:
      - mariadb-2
    build:
      context: ./app-2
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8002:8083
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://mariadb-2:3306/app?useSSL=false",
        "spring.datasource.username" : "user",
        "spring.datasource.password" : "mjuyhnbgtrfvcde",
        "spring.datasource.driver-class-name" : "org.mariadb.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    stdin_open: true
    tty: true

  # Database for the first application
  mariadb-1:
    image: 'mariadb:10.6.11'
    container_name: mariadb-1
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: mjuyhnbgtrfvcde
      MARIADB_DATABASE: app
      MARIADB_ROOT_PASSWORD: mjuyhnbgtrfvcde
    ports:
      - '3306:3306'
    volumes:
      - ${PWD}/mariadb-1/:/var/lib/mysql/
  
  # Database for the second application
  mariadb-2:
    image: 'mariadb:10.6.11'
    container_name: mariadb-2
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: mjuyhnbgtrfvcde
      MARIADB_DATABASE: app
      MARIADB_ROOT_PASSWORD: mjuyhnbgtrfvcde
    ports:
      - '3306:3306'
    volumes:
      - ${PWD}/mariadb-2/:/var/lib/mysql/
