version: '3.3'
services:
  mariadb-1:
    image: 'mariadb:10.6.11'
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_USER: user
      - MYSQL_PASSWORD: mjuyhnbgtrfvcde
      - MYSQL_DATABASE: app
      - MYSQL_ROOT_PASSWORD: mjuyhnbgtrfvcde
    ports:
      - '3306:3306'
    volumes:
      - ${PWD}/mariadb-1/:/var/lib/mysql/
  
  mariadb-2:
    image: 'mariadb:10.6.11'
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_USER: user
      - MYSQL_PASSWORD: mjuyhnbgtrfvcde
      - MYSQL_DATABASE: app
      - MYSQL_ROOT_PASSWORD: mjuyhnbgtrfvcde
    ports:
      - '3306:3306'
    volumes:
      - ${PWD}/mariadb-2/:/var/lib/mysql/
